### ISSUE TITLE
Entités Reward (Badge+Points) et récupération des badges et points remportés

### ISSUE THREAD

**Issue by pabloheigvd** [AMT-Project/project_2#40]
- [x] création de l'entité
- [x] endpoint permettant de voir qu'est-ce qu'un utilisateur a remporté
**Note**: aggrégation via une requête sql (groupBy user, user = username, Add(points))

**Comment by bonzonlu** [comment]
Les endpoints sont /leaderboards/{pointScale} et /users/{appUserId}/scores

- [ ] A tester
